MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHTS: ""   # 트레이너에서 model_zoo URL 또는 로컬 pkl로 지정
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  ROI_HEADS:
    NAME: "ROIHeads3D"        # ← 커스텀 ROIHeads
    NUM_CLASSES: 3            # Car/Pedestrian/Cyclist (필요시 변경)
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_TYPE: "ROIAlignV2"
    CONV_DIM: 256
    FC_DIM: 1024
    NORM: ""

DATASETS:
  TRAIN: ("zod3d_train",)
  TEST:  ("zod3d_val",)

DATALOADER:
  NUM_WORKERS: 4

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  STEPS: (6000, 8000)
  MAX_ITER: 9000
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 1000

INPUT:
  FORMAT: "BGR"

OUTPUT_DIR: "./output_zod3d_r50fpn"
